### ISSUE TITLE
Adding emulator support (PJ64, Mupen64 etc.)

### ISSUE THREAD

**Issue by AspectCave** [wermipls/mimi#10]
I know that it works fine on original hardware but are there any reasons why it doesn't run on emulator? I'm not a tech savy guy or anything but I think it'd be nice if it runs on emulator without issues
![Screenshot (827)](https://github.com/user-attachments/assets/71b5eb9e-04e0-45c8-a4b6-b3b0cf3817a5)

**Comment by wermipls** [comment]
Project64 2.x is way too inaccurate and will never be supported. Same with original Mupen64.

Use one of those (raphnetraw input plugin is **a must**, otherwise you're getting nonsensical and skewed test results, which defeats the purpose of the measurement):
- [Rosalie's Mupen GUI](https://github.com/Rosalie241/RMG/) (personal favorite)
- [simple64](https://github.com/simple64/simple64)

Additionally, the ROM should work perfectly in Ares, but as far as I know it lacks raphnetraw support, which makes it more or less useless for performing tests.
