### ISSUE TITLE
Intermittent Floating Point Exception on N64Digital-modded console

### ISSUE THREAD

**Issue by kerrymilan** [wermipls/mimi#9]
Had someone approach me with an issue in the Mimi ROM: Around 50% of the time, they're experiencing a floating point exception after the reading last input in the range test, just before the results are displayed. When performing a 3- or 5-sample test, it collects the first 2 or 4 samples without issue, then crashes at the end of the final one. They're using an N64Digital-modded console and reported that the issue first appeared after they installed the mod. 

Details I've been able to gather:

 * N64Digital-modded NTSC console
    * No clock mod
    * v2.1.34 firmware
    * Using HDMI output
 * Console has expansion pak installed
 * ROM is running on Everdrive X-5
 * Exception occurs at end of input read approx. 50% of the time
 * Exception occurs on both original release (2022-12-25) and latest (2023-04-13)
 * Exception did not occur prior to installation of N64Digital
 * Exception occurs with OEM controller as well as others, incl. Hori

I have a similar setup with two notable distinctions: Everdrive (X7 vs. X5) and FW version (2.1.43 vs. 2.1.34). I'm unable to replicate the issue. Do you have any ideas or thoughts?

https://user-images.githubusercontent.com/26632151/235372086-b8a43778-0881-49b8-9365-8290d509a01a.mp4

![IMG_1651](https://user-images.githubusercontent.com/26632151/235372093-0497a96a-864a-4e59-a47b-c75e57fe63a5.jpg)

**Comment by wermipls** [comment]
hi. quick investigation:
* looking at the disassembly, the exception seems to be caused by a sqrtf instr in `get_range_color_diagonal`
* cause appears to be inexact operation. from vr4300 manual:
> The FPU generates the inexact operation exception in the following cases.
> * If the accuracy of the rounded result drops
> * If the rounded result overflows
> * If the rounded result underflows and if the FS bit of FCR31 is set with the underflow and illegal operation exceptions disabled

from what i understand, if the exception is enabled it really should happen pretty much All The Time. so the question is why does it happen on their console and not everywhere else. looking at the code further, it doesn't really seem `__init_cop1` clears any enabled exceptions that could be left over from previously ran software (ed64 menu in this case?). the only other place where fcr31 gets set is in the interrupt end handler, which ig could be caused by stack corruption or so.

setting the the inexact op enable flag manually makes me able to reproduce the issue, so i made a build where i clear it instead. let me know if that resolves the issue

[mimi-11d82bc.zip](https://github.com/wermipls/mimi/files/11362541/mimi-11d82bc.zip)

**Comment by kerrymilan** [comment]
Sounds like your investigation led you in the right direction - this resolved the user’s issue. Thanks for once again lending your expertise. 

I’d love to dive deeper into the cause of this one but that seems difficult without being able to reproduce directly. Is there any way a bug in the Everdrive firmware could cause an issue like this? (I don’t see anything in their change log to support this, FWIW). Alternatively, could anything user-controllable on the Everdrive, like settings, wallpaper, or GS codes, be the culprit?

If you’re ok with the current fix, feel free to close this issue. Thanks again!
